---
#
# This playbook get VMWare Machine Guest info
#
- name: Get VMWare Machine Guest info
  hosts: localhost
  gather_facts: no
  
  tasks:
  - name: Get VMWare Machine Guest info
    community.vmware.vmware_vm_info:
      hostname: "172.16.64.140"
      validate_certs: False
    register: vm_info
    delegate_to: localhost
    connection: local
