name: ansible-lint
on: [push]
jobs:
  run-ansible-lint:
    name: Run ansible-lint
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get -y update
      - run: sudo apt-get -y install ansible ansible-lint python3-pip sshpass
      - run: pip3 install ansible==2.9.27
      - run: pip3 install ansible-lint==5.3.1
      - run: pip3 install pyvmomi
      - run: ansible-galaxy collection install community.vmware
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ansible-lint ${{ github.workspace }}/*
      - run: ansible-playbook -i 'localhost,' --syntax-check ${{ github.workspace }}/*yml
